global:
  scrape_interval:     15s # Default scrape is 15 seconds.

# A scrape configuration for Prometheus to monitor itself
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s # Used to override the default
    static_configs:
      - targets: ['localhost:9090']
      
# Example job for node_exporter
# - job_name: 'node_exporter'
#   static_configs:
#     - targets: ['node_exporter:9100']

# Example job for cadvisor
# - job_name: 'cadvisor'
#   static_configs:
#     - targets: ['cadvisor:8080']
